baseurl = "/"
languageCode = "nl-NL"
defaultContentLanguage = "nl"
title = "TkkrLab"
paginate = 5
#theme = "tkkrlab"
theme = "tkkrlab-mainroad"

logo = "/site_header.png"

enableRobotsTXT = true
#SectionPagesMenu = "main"
canonifyURLs = true

googleAnalytics = "UA-610785-7"

[Params]
  subtitle = "Hackerspace Enschede"
  description = "TkkrLab hackerspace"
  powered_by = ""
  hide_author = true
  images = []
  author = "Tkkrlab"
  copyright = ""
  avatar = "css/images/avatar.png"
  date_format = "02-01-2006"
  readmore = true
  post_navigation = true
  #postSections = ["nieuws","projects"]
  postSections = ["nieuws"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Nieuws"
    url = "/nieuws/"
    weight = 1

  [[menu.main]]
    name = "Projecten"
    url = "/projects/"
    weight = 3

  #[[menu.main]]  
  #  name = "Agenda"
  #  url = "https://tkkrlab.nl/wiki/TkkrLab:Current_events"
  #  weight = 5
  
  #[[menu.main]]  
  #  name = "Arduino cursus"
  #  url = "https://arduino.tkkrlab.space"
  #  weight = 6

  [[menu.main]]
    name = "Wiki"
    url = "https://www.tkkrlab.nl/wiki"
    weight = 7

[Params.widgets]
    search = false
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false
    newsletter = true
    contact = true
    meta = true
    twitter = true
    social_facebook = "TkkrLab"
    social_twitter = "tkkrlab"
    social_github = "tkkrlab"
    social_youtube = "TkkrLab"
    social_flickr = "TkkrLab"
    social_linkedin = "groups/3906596"
